/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#1a1c1c',
        'on-secondary': '#2f3131',
        surface: '#131315',
        'on-primary-container': '#72778d',
        'on-tertiary-fixed': '#07006c',
        'on-tertiary-container': '#6467f2',
        'secondary-fixed-dim': '#c6c6c7',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#c0c1ff',
        primary: '#c0c6de',
        'surface-tint': '#c0c6de',
        'on-tertiary': '#1000a9',
        'surface-container-lowest': '#0e0e0f',
        'on-primary-fixed-variant': '#40465a',
        'surface-variant': '#353436',
        'outline-variant': '#46464c',
        'on-secondary-container': '#b4b5b5',
        'inverse-primary': '#585e73',
        'surface-bright': '#39393a',
        'tertiary-container': '#01002e',
        'surface-container-highest': '#353436',
        'on-primary-fixed': '#151b2d',
        secondary: '#c6c6c7',
        tertiary: '#c0c1ff',
        'primary-container': '#020617',
        'surface-dim': '#131315',
        'inverse-surface': '#e5e2e3',
        'secondary-fixed': '#e2e2e2',
        'on-surface': '#e5e2e3',
        'on-secondary-fixed-variant': '#454747',
        'on-surface-variant': '#c6c6cd',
        'tertiary-fixed': '#e1e0ff',
        'surface-container': '#201f21',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'surface-container-high': '#2a2a2b',
        outline: '#909097',
        'surface-container-low': '#1b1b1d',
        'primary-fixed-dim': '#c0c6de',
        'on-error': '#690005',
        'secondary-container': '#454747',
        'inverse-on-surface': '#303032',
        'on-background': '#e5e2e3',
        'on-error-container': '#ffdad6',
        'on-primary': '#2a3043',
        error: '#ffb4ab',
        'primary-fixed': '#dce1fb',
        background: '#131315',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '32px',
        'container-max': '1440px',
        'section-gap': '160px',
        'margin-mobile': '24px',
        unit: '8px',
        'margin-desktop': '80px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'label-caps': ['Geist', 'sans-serif'],
        'body-sm': ['DM Sans', 'sans-serif'],
        'display-mobile': ['Montserrat', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'body-lg': ['DM Sans', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'label-caps': [
          '12px',
          { lineHeight: '1.0', letterSpacing: '0.2em', fontWeight: '500' },
        ],
        'body-sm': [
          '14px',
          { lineHeight: '1.6', letterSpacing: '0.02em', fontWeight: '400' },
        ],
        'display-mobile': [
          '42px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'display-lg': [
          '80px',
          { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' },
        ],
        'body-lg': [
          '18px',
          { lineHeight: '1.8', letterSpacing: '0.01em', fontWeight: '400' },
        ],
        'headline-md': [
          '32px',
          { lineHeight: '1.3', letterSpacing: '0.05em', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [],
}
